# Generated by Django 5.0.1 on 2024-03-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tasklist_assogned_by_alter_tasklist_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='assogned_by',
            new_name='assigned_by',
        ),
    ]
