# Generated by Django 5.0.1 on 2024-03-16 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_assogned_by_tasklist_assigned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskList',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='TasksUnderTaskList',
            new_name='Tasks',
        ),
        migrations.DeleteModel(
            name='TaskAssignToGroup',
        ),
    ]
