# Generated by Django 5.0.1 on 2024-03-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_tasklist_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigntoemployee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='taskassigntoemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='app.employee'),
        ),
    ]
