# Generated by Django 5.0.1 on 2024-03-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_taskassigntoemployee_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('TeamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teamleader')),
            ],
        ),
    ]
