# Generated by Django 5.0.1 on 2024-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teamleader_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamleader',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='leader',
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('team_leader', 'team_leader'), ('manager', 'manager'), ('admin', 'admin')], default='employee', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
