# Generated by Django 5.0.1 on 2024-03-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_teamleader_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
