# Generated by Django 5.0.1 on 2024-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivitysheet',
            name='billing_acheived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dailyactivitysheet',
            name='billing_projected',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dailyactivitysheet',
            name='collection_acheived',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='dailyactivitysheet',
            name='collection_projected',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
