# Generated by Django 5.0.1 on 2024-03-25 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dailyactivitysheet_billing_acheived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitysheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
