# Generated by Django 5.0.1 on 2024-03-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_dailyactivitysheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitysheet',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
