# Generated by Django 5.0.1 on 2024-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_time_dailyactivitysheet_assigned_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivitysheet',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
