# Generated by Django 5.0.1 on 2024-03-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_employee_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportingTo',
        ),
    ]
