# Generated by Django 5.0.1 on 2024-03-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_reportingto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='app.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('employee', 'employee'), ('team_leader', 'team_leader'), ('manager', 'manager'), ('admin', 'admin')], default='employee', max_length=100),
        ),
        migrations.DeleteModel(
            name='ReportingTo',
        ),
    ]
