# Generated by Django 5.0.1 on 2024-03-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_reporting_manager_employee_reporting_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
