# Generated by Django 5.0.1 on 2024-03-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
