# Generated by Django 5.0.1 on 2024-03-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_project_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assigned_by',
            new_name='created_by',
        ),
    ]
