# Generated by Django 5.0.1 on 2024-04-04 03:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_dailyactivitysheet_activitysheet_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysheet',
            name='billing_acheived',
        ),
        migrations.RemoveField(
            model_name='activitysheet',
            name='billing_projected',
        ),
        migrations.RemoveField(
            model_name='activitysheet',
            name='collection_acheived',
        ),
        migrations.RemoveField(
            model_name='activitysheet',
            name='collection_projected',
        ),
        migrations.AlterField(
            model_name='activitysheet',
            name='action_planned',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='activitysheet',
            name='assigned_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitysheet',
            name='estimated_completed_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('billing_projected', models.IntegerField(blank=True, default=0)),
                ('billing_acheived', models.IntegerField(blank=True, default=0)),
                ('collection_projected', models.IntegerField(blank=True, default=0)),
                ('collection_acheived', models.IntegerField(blank=True, default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
