# Generated by Django 5.0.1 on 2024-04-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_activitysheet_billing_acheived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassigntoemployee',
            old_name='assigned_date',
            new_name='created_date',
        ),
    ]
